# Change these first
owner: ilstax # Your GitHub organization or username, where this repository lives
repo: boz-status # The name of this repository
assignees:
  - iLStAx
sites:
  - name: Bournout Zero
    url: https://www.burnout-zero.com
  - name: App Burnout Zero
    url: https://app.burnout-zero.com
  - name: Dev Burnout Zero
    url: https://dev.burnout-zero.com
  - name: Back-dev Burnout Zero
    url: https://back-dev.burnout-zero.com/healthz
  - name: Back Burnout Zero
    url: https://back.burnout-zero.com/healthz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /boz-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BozStatus
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /boz-status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
